kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: maven # 定义流水线名称

trigger:
  branch:
    - main
steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: package # 流水线名称
    image: golang:latest # 定义创建容器的Docker镜像
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: go-cache
        path: /go # 将go下载依赖的目录挂载出来，防止重复下载
      - name: go-build
        path: /app/build # 将应用打包好的物料挂载出来
    commands: # 定义在Docker容器中执行的shell 命令
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o tradingbot-linux main.go # 应用打包命令    /drone/src/xxx?
      - ls # 查看当前目录下的文件
      #      - cd /app/build
      - cp -r tradingbot-linux  /app/build/new_tradingbot-linux
volumes: # 定义流水线挂载目录，用于共享数 据
  - name: go-build
    host:
      path: /app/tradingbot #挂载的目 录
  - name: go-cache
    host:
      path: /app/boot/go_cache
